def romanToInt(s):
        i=0
        sum=0
        s=s+'Q'
        while s[i]!='Q':
                if(s[i]=='I'):
                    if(s[i+1]=='V'):
                        sum+=4
                        i+=2
                    elif(s[i+1]=='X'):
                        sum+=9
                        i+=2
                    else:
                        sum+=1
                        i+=1
                elif(s[i]=='V'):
                    sum+=5
                    i+=1
                elif(s[i]=='X'):
                    if(s[i+1]=='L'):
                        sum+=40
                        i+=2
                    elif(s[i+1]=='C'):
                        sum+=90
                        i+=2
                    else:
                        sum+=10
                        i+=1
                elif(s[i]=='L'):
                        sum+=50
                        i+=1
                elif(s[i]=='C'):
                    if(s[i+1]=='D'):
                        sum+=400
                        i+=2
                    elif(s[i+1]=='M'):
                        sum+=900
                        i+=2
                    else:
                        sum+=100
                        i+=1
                elif(s[i]=='D'):
                    sum+=500
                    i+=1
                elif(s[i]=='M'):
                    sum+=1000
                    i+=1
                print('sum:-',sum,'i:-',i)
        print('sum:-',sum)
        return sum
print(romanToInt("VI"))
